/**
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveBarcodeapiClient) {
      root.CloudmersiveBarcodeapiClient = {};
    }
    root.CloudmersiveBarcodeapiClient.BarcodeAdvancedResultItem = factory(root.CloudmersiveBarcodeapiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BarcodeAdvancedResultItem model module.
   * @module model/BarcodeAdvancedResultItem
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>BarcodeAdvancedResultItem</code>.
   * Advanced barcode scan result instance
   * @alias module:model/BarcodeAdvancedResultItem
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BarcodeAdvancedResultItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BarcodeAdvancedResultItem} obj Optional instance to populate.
   * @return {module:model/BarcodeAdvancedResultItem} The populated <code>BarcodeAdvancedResultItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RawText')) {
        obj['RawText'] = ApiClient.convertToType(data['RawText'], 'String');
      }
      if (data.hasOwnProperty('BarcodeType')) {
        obj['BarcodeType'] = ApiClient.convertToType(data['BarcodeType'], 'String');
      }
    }
    return obj;
  }

  /**
   * The barcode text
   * @member {String} RawText
   */
  exports.prototype['RawText'] = undefined;
  /**
   * Type of the barcode; supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB.
   * @member {String} BarcodeType
   */
  exports.prototype['BarcodeType'] = undefined;



  return exports;
}));


