/**
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BarcodeQRResultItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BarcodeQRResultItem'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveBarcodeapiClient) {
      root.CloudmersiveBarcodeapiClient = {};
    }
    root.CloudmersiveBarcodeapiClient.BarcodeScanQRAdvancedResult = factory(root.CloudmersiveBarcodeapiClient.ApiClient, root.CloudmersiveBarcodeapiClient.BarcodeQRResultItem);
  }
}(this, function(ApiClient, BarcodeQRResultItem) {
  'use strict';




  /**
   * The BarcodeScanQRAdvancedResult model module.
   * @module model/BarcodeScanQRAdvancedResult
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>BarcodeScanQRAdvancedResult</code>.
   * Result of the advanced QR barcode scan
   * @alias module:model/BarcodeScanQRAdvancedResult
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>BarcodeScanQRAdvancedResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BarcodeScanQRAdvancedResult} obj Optional instance to populate.
   * @return {module:model/BarcodeScanQRAdvancedResult} The populated <code>BarcodeScanQRAdvancedResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('ResultBarcodes')) {
        obj['ResultBarcodes'] = ApiClient.convertToType(data['ResultBarcodes'], [BarcodeQRResultItem]);
      }
      if (data.hasOwnProperty('BarcodeCount')) {
        obj['BarcodeCount'] = ApiClient.convertToType(data['BarcodeCount'], 'Number');
      }
      if (data.hasOwnProperty('ErrorMessage')) {
        obj['ErrorMessage'] = ApiClient.convertToType(data['ErrorMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if the operation was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Results of performing the QR barcode scan operation
   * @member {Array.<module:model/BarcodeQRResultItem>} ResultBarcodes
   */
  exports.prototype['ResultBarcodes'] = undefined;
  /**
   * Number of barcodes read
   * @member {Number} BarcodeCount
   */
  exports.prototype['BarcodeCount'] = undefined;
  /**
   * Error message if any
   * @member {String} ErrorMessage
   */
  exports.prototype['ErrorMessage'] = undefined;



  return exports;
}));


